# -*- coding: utf-8 -*-
"""crud_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zAkOstfLM4zlg1j8_-Rp_qwyM1hkzpcA
"""

#Connect to the MySQL server
import mysql.connector

try:
    connection = mysql.connector.connect(
        host="localhost",
        user="youruser",
        password="yourpassword",
        database="BetterWorldBooksDB")

    if connection.is_connected():
        print("Connected to the MySQL database successfully")

    #Database Operation 1: Read all books in BetterWorld Books Inventory
    #Create a cursor object to interact with the database
    cursor = connection.cursor()

    def read_data():
        select_query = "SELECT book_id, title, price, book_condition FROM Book"
        cursor.execute(select_query)
        books = cursor.fetchall()

        if not books:
            print("No books found in BetterWorld Books Inventory.")
            return

        print("Inventory of Books at BetterWorld Books")

        for book in books:
            print(
                f"Book ID: {book[0]}, Title: {book[1]}, "
                f"Price (CAD$): ${book[2]}, Condition: {book[3]}")

        print("Book record retrieved successfully.")

    #Database Operation 2: Add a book in the BetterWorld Books Inventory
    def write_data():
        print("Add a book in the BetterWorld Books Inventory")
        insert_query = "INSERT INTO Book (book_id, title, price, book_condition, publication_year, isbn, author_id, genre_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)"
        book_data = (16, "Wicked", 24.99, "New", 2026, 13579246810123, 15, 12)

        book_id, title, price, book_condition, publication_year, isbn, author_id, genre_id = book_data

        if title == "" or book_condition == "" or isbn == "":
            print("Error: Title, book condition, and ISBN cannot be blank.")
            return

        if price <= 0:
            print("Error: Price must be greater than 0.")
            return

        cursor.execute(insert_query, book_data)
        connection.commit()

        print("New book record inserted successfully.")

    #Database Operation 3: Update a book record in BetterWorld Books Inventory
    def update_data():
        print("Update a book record in BetterWorld Books Inventory")

        update_query = "UPDATE Book SET price = %s, book_condition = %s WHERE book_id = %s"
        data_update = (22.99, "Used - Like New", 16)
        price, book_condition, book_id = data_update

        if price <= 0:
            print("Error: Price must be greater than 0.")
            return

        if book_condition == "":
            print("Error: Book condition cannot be blank.")
            return

        cursor.execute(update_query, data_update)
        connection.commit()

        if cursor.rowcount == 0:
            print("No book found with that ID.")
        else:
            print("Book record updated successfully.")


    #Database Operation 4: Delete a book record from BetterWorld Books Inventory
    def delete_data():
        print("Delete a book record from BetterWorld Books Inventory")

        delete_query = "DELETE FROM Book WHERE book_id = %s"
        book_id = (16,)

        cursor.execute(delete_query, book_id)
        connection.commit()

        if cursor.rowcount == 0:
            print("No book found with that ID.")
        else:
            print("Book record deleted successfully.")

    #Database Operation 5: Calculate average prices of all books in BetterWorld Books Inventory
    def others1():
        select_query = "SELECT AVG(price) FROM Book"
        cursor.execute(select_query)
        books = cursor.fetchall()

        print("Average Book Price:")
        for book in books:
            print(f"Average Price (CAD$): ${book[0]}")

        print("Other query executed successfully.")

    def main():
        while True:
            print("\nMenu:")
            print("1. Read all books in BetterWorld Books Inventory")
            print("2. Add a book in the BetterWorld Books Inventory")
            print("3. Update a book record in BetterWorld Books Inventory")
            print("4. Delete a book record from BetterWorld Books Inventory")
            print("5. Calculate average price of all books in BetterWorld Books Inventory")
            print("6. Exit")

            choice = input("Enter your choice: ")

            if choice == '1':
                read_data()
            elif choice == '2':
                write_data()
            elif choice == '3':
                update_data()
            elif choice == '4':
                delete_data()
            elif choice == '5':
                others1()
            elif choice == '6':
                print("Exiting program.")
                break
            else:
                print("Invalid choice. Please select a valid option.")

    if __name__ == "__main__":
        main()

except mysql.connector.Error as e:
    print("Error:", e)

finally:
    # Close the database connection
    if 'connection' in locals() and connection.is_connected():
        cursor.close()
        connection.close()
        print("Connection to MySQL database closed")
